NUTRIMENT_NAMES = (
    "fat",
    "saturated-fat",
    "carbohydrates",
    "sugars",
    "fiber",
    "proteins",
    "salt",
    "energy-kcal",
    "fruits-vegetables-nuts",
)


EXCLUDE_LIST_CATEGORIES = """en:alcoholic-beverages
en:artisan-products
en:baby-foods
en:bakery-products
en:bee-products
en:belgian-meat-products
en:beverages
en:biscuits-and-cakes
en:breaded-products
en:breakfasts
en:canned-foods
en:canned-plant-based-foods
en:carbonated-drinks
en:cereal-grains
en:cereals-and-potatoes
en:cereals-and-their-products
en:chips-and-fries
en:christmas-foods-and-drinks
en:cocoa-and-its-products
en:condiments
en:coriander-products
en:dairies
en:desserts
en:dried-plant-based-foods
en:dried-products
en:dried-products-to-be-rehydrated
en:farming-products
en:fats
en:fenugreek-products
en:fermented-foods
en:fermented-milk-products
en:fish-and-meat-and-eggs
en:fishes
en:freeze-dried-plant-based-foods
en:french-cheeses
en:fresh-foods
en:fresh-plant-based-foods
en:fried-foods
en:fried-plant-based-foods
en:frozen-foods
en:frozen-plant-based-foods
en:frozen-plant-based-foods-mixes
en:frozen-snacks-and-starters
en:fruit-and-fruit-seed-oils
en:fruit-and-vegetable-preserves
en:fruit-based-beverages
en:fruits
en:fruits-and-vegetables-based-foods
en:fruits-based-foods
en:garlic-and-their-products
en:groceries
en:halloween-foods-and-drinks
en:hot-beverages
en:italian-cheeses
en:italian-meat-products
en:juices-and-nectars
en:legumes
en:legumes-and-their-products
en:licensed-products
en:meals
en:meals-with-meat
en:meat-based-products
en:meats
en:mountain-products
en:mushrooms-and-their-products
en:non-alcoholic-beverages
en:non-dairy-fermented-foods
en:non-food-products
en:nutmeg-tree-products
en:nuts-and-their-products
en:olive-tree-products
en:onions-and-their-products
en:open-products-facts
en:pizzas-pies-and-quiches
en:plant-based-beverages
en:plant-based-foods
en:plant-based-foods-and-beverages
en:plant-based-spreads
en:polish-meat-products
en:poultries
en:prepared-meats
en:products-with-reduced-salt
en:products-without-gluten
en:pumpkin-and-squash-plant-products
en:pumpkin-plant-products
en:pumpkin-seeds-and-their-products
en:pumpkins-and-their-products
en:salty-snacks
en:sauces
en:seafood
en:seaweed-products
en:seaweeds-and-their-products
en:seeds
en:semi-preserved-foods
en:snacks
en:snacks-and-desserts-for-babies
en:spanish-bakery-products
en:spanish-meat-products
en:spreads
en:stevia-and-their-products
en:sunflower-seeds-and-their-products
en:sweet-snacks
en:sweet-spreads
en:sweeteners
en:tomatoes-and-their-products
en:tomatoes-and-tomato-products
en:vegetable-based-foods-and-beverages
en:vegetable-fats
en:vegetable-oils
en:vegetables-based-foods""".splitlines()
