import matplotlib.pyplot as plt
import pandas as pd


def plot_training_stat(stats: pd.DataFrame, stat: str, ax = None):
    """
    Parameters
    ----------
    stats : pd.DataFrame
        Tensorflow statistics as generated by `tf.keras.callbacks.CSVLogger`.

    stat : str
        Name of the statistic to plot (e.g. 'loss', 'precision', ...).

    plt : matplotlib.axes.Axes, optional
        Axes to draw the plot on. Will draw on the current plot if None.
    """
    if not ax:
        ax = plt.gca()

    ax.plot(stats['epoch'], stats[stat])
    ax.plot(stats['epoch'], stats[f"val_{stat}"])
    ax.set_title(stat)
    ax.set_ylabel(stat)
    ax.set_xlabel('Epoch')
    ax.legend(['train' , 'validation'] , loc='upper right')
